export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const USER_UPDATE_NAME = 'USER_UPDATE_NAME';
export const DELETE_USER = 'DELETE_USER';

export const GET_ALL_TRANSACTIONS = 'GET_ALL_TRANSACTIONS'; 

export const AUTH_ERROR_OCCURRED = 'AUTH_ERROR_OCCURRED';
export const MARKET_ERROR_OCCURRED = 'MARKET_ERROR_OCCURRED';
export const PURCHASED_ERROR_OCCURRED = 'PURCHASED_ERROR_OCCURRED';
export const USER_ERROR_OCCURRED = 'USER_ERROR_OCCURRED';
export const TRANSACTION_ERROR_OCCURRED = 'TRANSACTION_ERROR_OCCURRED';